steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  - name: 'gcr.io/cloud-builders/npm'
    env:
      - 'VITE_REACT_APP_CLIENT_ID=a605ffae-592a-4096-b029-78ba66b6d614'
      - 'VITE_REACT_APP_TENANT_NAME=sfkitdevb2c'
      - 'VITE_REACT_APP_SIGNUPSIGNIN_USER_FLOW=B2C_1_signupsignin1'
      - 'VITE_REACT_APP_EDITPROFILE_USER_FLOW=B2C_1_profile_editing'
      - 'VITE_REACT_APP_RESETPASSWORD_USER_FLOW=B2C_1_reset_password'
      - 'VITE_REACT_APP_API_BASE_URL=https://sfkit-website-dev-bhj5a4wkqa-uc.a.run.app'
    args: ['run', 'build']
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', './dist/*', 'gs://dev.sfkit.org']