substitutions:
  _DEPLOY_REGION: us-central1
  _APP_VERSION: latest
  _BUILD_VERSION: latest
  _SERVICE_NAME: sfkit-react-dev
  _SERVICE_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _IMAGE: ${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true

steps:
  - name: gcr.io/cloud-builders/docker
    script: >-
      docker buildx create --use --driver docker-container &&
      docker buildx build --push -t $_IMAGE:$SHORT_SHA
        --cache-from type=registry,ref=$_IMAGE:cache
        --cache-to type=registry,ref=$_IMAGE:cache,mode=max
        --build-arg APP_VERSION=$SHORT_SHA
        --build-arg BUILD_VERSION=$SHORT_SHA .

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    script: >-
      gcloud run deploy $_SERVICE_NAME
        --image $_IMAGE:$SHORT_SHA
        --region $_SERVICE_REGION
        --min-instances 1
