steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args: ['build',
           '--build-arg', 'APP_VERSION=$_APP_VERSION',
           '--build-arg', 'BUILD_VERSION=$_BUILD_VERSION',
           '--build-arg', 'SERVICE_NAME=$_SERVICE_NAME',
           '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA',
           '.']

  - id: Push
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=us-central1'
      - '--min-instances=1'
      - '--quiet'

  - id: SetIAM
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - add-iam-policy-binding
      - $_SERVICE_NAME
      - '--region=us-central1'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _DEPLOY_REGION: us-central1
  _APP_VERSION: latest
  _BUILD_VERSION: latest
  _SERVICE_NAME: sfkit-react-dev

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - sfkit-react
