substitutions:
  _DEPLOY_REGION: us-central1
  _APP_VERSION: latest
  _BUILD_VERSION: latest
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: sfkit-react
  _SERVICE_REGION: us-central1
  _SERVICE_ACCOUNT: ${_SERVICE_NAME}-sa@${PROJECT_ID}.iam.gserviceaccount.com
  _IMAGE: ${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}
  _CUSTOM_DOMAIN: ""

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true

steps:
  - name: gcr.io/cloud-builders/docker
    script: >-
      docker buildx create --use --driver docker-container &&
      docker buildx build --push -t $_IMAGE:$SHORT_SHA
      --cache-from type=registry,ref=$_IMAGE:cache
      --cache-to type=registry,ref=$_IMAGE:cache,mode=max
      --build-arg APP_VERSION=$SHORT_SHA
      --build-arg BUILD_VERSION=$SHORT_SHA .
      --build-arg SERVICE_NAME=$_SERVICE_NAME

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    script: >-
      gcloud run deploy $_SERVICE_NAME
      --image $_IMAGE:$SHORT_SHA
      --region $_SERVICE_REGION
      --service-account $_SERVICE_ACCOUNT
      --min-instances 1
      --max-instances 5
      && ([ -z "$_CUSTOM_DOMAIN" ] ||
      gcloud beta run domain-mappings create \
        --service $_SERVICE_NAME \
        --region $_SERVICE_REGION \
        --domain $_CUSTOM_DOMAIN)
