FROM node:lts-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_REACT_APP_CLIENT_ID
ARG VITE_REACT_APP_TENANT_NAME
ARG VITE_REACT_APP_SIGNUPSIGNIN_USER_FLOW
ARG VITE_REACT_APP_EDITPROFILE_USER_FLOW
ARG VITE_REACT_APP_RESETPASSWORD_USER_FLOW
ARG VITE_REACT_APP_API_BASE_URL

ENV VITE_REACT_APP_CLIENT_ID=$VITE_REACT_APP_CLIENT_ID
ENV VITE_REACT_APP_TENANT_NAME=$VITE_REACT_APP_TENANT_NAME
ENV VITE_REACT_APP_SIGNUPSIGNIN_USER_FLOW=$VITE_REACT_APP_SIGNUPSIGNIN_USER_FLOW
ENV VITE_REACT_APP_EDITPROFILE_USER_FLOW=$VITE_REACT_APP_EDITPROFILE_USER_FLOW
ENV VITE_REACT_APP_RESETPASSWORD_USER_FLOW=$VITE_REACT_APP_RESETPASSWORD_USER_FLOW
ENV VITE_REACT_APP_API_BASE_URL=$VITE_REACT_APP_API_BASE_URL

RUN npm run lint
RUN npm run build

ARG APP_VERSION=latest
ARG BUILD_VERSION=latest

RUN echo "{\"appVersion\": \"$APP_VERSION\", \"buildVersion\": \"$BUILD_VERSION\"}" > dist/version

FROM us.gcr.io/broad-dsp-gcr-public/base/nginx:distroless

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html/