map $uri $cache_control {
    default "no-cache, no-store, must-revalidate";
    ~^/(assets|latest/meta-data) "max-age=31536000, immutable";
}

map $uri $unsafe_inline {
    default "";
    ~^/__/auth "'unsafe-inline'";
}

server {
    listen       8080;
    server_tokens off;

    # Caching
    add_header Cache-Control $cache_control always;

    # Security
    add_header Content-Security-Policy "default-src 'none'; script-src 'self' https://apis.google.com $unsafe_inline; connect-src 'self' https://${FIREBASE_AUTH_DOMAIN} ${API_BASE_URL} https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://www.googleapis.com; font-src 'self'; frame-src https://www.youtube-nocookie.com https://${FIREBASE_AUTH_DOMAIN}/__/auth/; frame-ancestors 'self'; img-src 'self' blob: data:; style-src 'self' $unsafe_inline; base-uri 'self'; form-action 'self';" always;
    add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;

        location = /version {
            access_log off;
        }
    }

    location /__/auth {
        proxy_pass https://${FIREBASE_AUTH_UPSTREAM};
        proxy_set_header Host ${FIREBASE_AUTH_UPSTREAM};
    }

    # needed to satisfy Zap
    location /latest/meta-data {
        return 404;
    }

    location = /status {
        access_log off;
        return 200;
    }
}
